### ISSUE TITLE
Suggestion: use titaniumifier

### ISSUE THREAD

**Issue by yuchi** [CodlyLabs/ti.states#1]
This looks a perfect candidate for being a [_titaniumified_ package](https://github.com/smclab/titaniumifier). You’ll get [_gitTio_](http://gitt.io/contributors) support for free also :)

You can get yourself started [at the Wiki documentation](https://github.com/smclab/titaniumifier/wiki).

Please let me know if you have any issue in the process.

**Comment by HazemKhaled** [comment]
+1

**Comment by drmas** [comment]
Done
